# Generated by Django 2.2.7 on 2020-03-26 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='parent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('father_name', models.TextField(max_length=20)),
                ('mothers_name', models.TextField(max_length=20)),
                ('occupation', models.TextField()),
                ('contact_info', models.IntegerField()),
                ('alternate_contact_info', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('religion', models.TextField()),
                ('nationality', models.TextField()),
                ('address', models.TextField()),
                ('country', models.TextField()),
                ('state', models.TextField()),
                ('pincode', models.IntegerField()),
                ('image', models.ImageField(upload_to='students')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.TextField(max_length=15)),
                ('middlename', models.TextField(max_length=15)),
                ('lastname', models.TextField(max_length=15)),
                ('gender', models.TextField()),
                ('dateofbirth', models.DateField()),
                ('email', models.EmailField(max_length=254)),
                ('religion', models.TextField()),
                ('phone_number', models.IntegerField()),
                ('image', models.ImageField(upload_to='students')),
                ('registration_id', models.TextField()),
                ('class_name', models.TextField()),
                ('class_division', models.TextField()),
                ('roll_number', models.IntegerField()),
                ('last_school', models.TextField()),
                ('last_std', models.TextField()),
                ('last_marks_obtained', models.DecimalField(decimal_places=2, max_digits=8)),
                ('sports_intreseted', models.TextField()),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studentdashboard.parent')),
            ],
        ),
    ]
