# Generated by Django 2.2.7 on 2020-03-27 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentdashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parent',
            name='alternate_contact_info',
            field=models.DecimalField(decimal_places=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='parent',
            name='contact_info',
            field=models.DecimalField(decimal_places=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='student',
            name='phone_number',
            field=models.DecimalField(decimal_places=0, max_digits=12),
        ),
    ]
