# Generated by Django 2.2.7 on 2020-03-27 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentdashboard', '0002_auto_20200327_1159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='last_marks_obtained',
            field=models.TextField(),
        ),
    ]
