# Generated by Django 2.2.7 on 2020-03-30 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentdashboard', '0003_auto_20200327_1200'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='attendence_blocked',
            field=models.TextField(default='No'),
            preserve_default=False,
        ),
    ]
