# Generated by Django 2.2.7 on 2020-03-30 09:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admindashboard', '0005_timetable'),
        ('teacherdashboard', '0003_delete_attendance'),
        ('studentdashboard', '0004_student_attendence_blocked'),
    ]

    operations = [
        migrations.CreateModel(
            name='attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_present', models.BooleanField()),
                ('remarks', models.TextField()),
                ('date_marked', models.DateField()),
                ('class_details', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='admindashboard.Class')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='admindashboard.ClassSection')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='studentdashboard.Student')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='admindashboard.Subject')),
                ('teacher_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='teacherdashboard.teachers')),
            ],
        ),
    ]
