# Generated by Django 2.2.7 on 2020-03-30 14:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('studentdashboard', '0006_auto_20200330_1952'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='login_details',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='student',
            name='class_division',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admindashboard.ClassSection'),
        ),
    ]
