# Generated by Django 2.2.7 on 2020-04-03 06:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admindashboard', '0011_auto_20200331_1819'),
        ('studentdashboard', '0009_auto_20200331_1539'),
    ]

    operations = [
        migrations.CreateModel(
            name='marks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_type', models.TextField()),
                ('marks_obtained', models.TextField()),
                ('total_marks', models.TextField()),
                ('class_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admindashboard.Class')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admindashboard.ClassSection')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studentdashboard.Student')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admindashboard.Subject')),
            ],
        ),
    ]
