# Generated by Django 2.2.7 on 2020-03-29 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.TextField()),
                ('announced_for', models.TextField()),
                ('subject', models.TextField()),
                ('description', models.TextField()),
            ],
        ),
    ]
