# Generated by Django 2.2.7 on 2020-03-29 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admindashboard', '0002_class'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.TextField()),
                ('section_name', models.TextField()),
                ('section_code', models.TextField()),
                ('description', models.TextField()),
            ],
        ),
    ]
