# Generated by Django 2.2.7 on 2020-03-29 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admindashboard', '0003_classsection'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('code', models.TextField()),
                ('teacher', models.TextField()),
                ('subject_class', models.TextField()),
                ('description', models.TextField()),
            ],
        ),
    ]
