# Generated by Django 2.2.7 on 2020-03-29 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admindashboard', '0004_subject'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.TextField()),
                ('time_slot', models.TextField()),
                ('class_name', models.TextField()),
                ('class_section', models.TextField()),
                ('subject_name', models.TextField()),
                ('teacher', models.TextField()),
                ('classroom', models.TextField()),
            ],
        ),
    ]
