# Generated by Django 2.2.7 on 2020-03-30 10:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admindashboard', '0006_auto_20200330_1623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classsection',
            name='class_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='admindashboard.Class'),
        ),
    ]
