# Generated by Django 2.2.7 on 2020-03-31 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admindashboard', '0009_auto_20200331_1814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='subject_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admindashboard.Class'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacherdashboard.teachers'),
        ),
    ]
