# Generated by Django 2.2.7 on 2020-03-31 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teacherdashboard', '0004_teachers_username'),
        ('admindashboard', '0010_auto_20200331_1815'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='class',
            name='class_teacher',
        ),
        migrations.AddField(
            model_name='classsection',
            name='section_teacher',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='teacherdashboard.teachers'),
            preserve_default=False,
        ),
    ]
