# Generated by Django 2.2.7 on 2020-04-03 11:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admindashboard', '0011_auto_20200331_1819'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='subject_section',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='admindashboard.ClassSection'),
            preserve_default=False,
        ),
    ]
