# Generated by Django 2.2.7 on 2020-03-28 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='teachers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.TextField(max_length=15)),
                ('middlename', models.TextField(max_length=15)),
                ('lastname', models.TextField(max_length=15)),
                ('gender', models.TextField()),
                ('dateofbirth', models.DateField()),
                ('email', models.EmailField(max_length=254)),
                ('religion', models.TextField()),
                ('phone_number', models.DecimalField(decimal_places=0, max_digits=12)),
                ('image', models.ImageField(upload_to='teachers')),
                ('address', models.TextField()),
                ('address_alternate', models.TextField()),
                ('country', models.TextField()),
                ('state', models.TextField()),
                ('pincode', models.IntegerField()),
                ('alternate_phone', models.DecimalField(decimal_places=0, max_digits=12)),
                ('highest_degree', models.TextField()),
                ('highest_degree_university', models.TextField()),
                ('highest_degree_yearpassed', models.TextField()),
                ('highest_degree_cgpa', models.TextField()),
                ('degree', models.TextField()),
                ('university', models.TextField()),
                ('yearpassed', models.TextField()),
                ('cgpa', models.TextField()),
            ],
        ),
    ]
