# Generated by Django 2.2.7 on 2020-03-30 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacherdashboard', '0002_attendance'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Attendance',
        ),
    ]
