# Generated by Django 2.2.7 on 2020-03-30 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacherdashboard', '0003_delete_attendance'),
    ]

    operations = [
        migrations.AddField(
            model_name='teachers',
            name='username',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
