# Generated by Django 2.2.7 on 2020-03-15 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventsnews',
            name='featured',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
    ]
