# Generated by Django 2.2.7 on 2020-03-16 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0002_eventsnews_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventsnews',
            name='eventtype',
            field=models.TextField(default='academic'),
            preserve_default=False,
        ),
    ]
