# Generated by Django 2.2.7 on 2020-03-21 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0003_eventsnews_eventtype'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeaturedEventsNews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('date', models.DateField()),
                ('location', models.TextField()),
                ('description', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='eventsnews',
            name='featured',
        ),
    ]
