# Generated by Django 2.2.7 on 2020-03-22 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0006_news'),
    ]

    operations = [
        migrations.AddField(
            model_name='teachers',
            name='mobile',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
