# Generated by Django 2.2.7 on 2020-03-25 06:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0009_imagegallery'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=30)),
                ('datetime', models.DateTimeField()),
                ('location', models.TextField(max_length=25)),
                ('description', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='eventsnews',
            name='eventtype',
            field=models.TextField(choices=[('SP', 'Sports'), ('AD', 'Admission'), ('AC', 'Academic')]),
        ),
        migrations.AlterField(
            model_name='imagegallery',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontend.EventDetail'),
        ),
    ]
