# Generated by Django 2.2.7 on 2020-03-25 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0011_auto_20200325_1216'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventdetail',
            name='displayImage',
            field=models.ImageField(default=0, upload_to='pics'),
            preserve_default=False,
        ),
    ]
