# Generated by Django 2.2.7 on 2020-06-21 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0015_gallery_displayimage'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Teachers',
            new_name='Staffs',
        ),
    ]
