# Generated by Django 2.2.7 on 2020-06-21 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0016_auto_20200621_1958'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staffs',
            old_name='subject',
            new_name='designation',
        ),
    ]
