# Generated by Django 2.2.7 on 2020-07-10 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0017_auto_20200621_2023'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventdetail',
            name='videourl',
            field=models.TextField(default='', max_length=500),
            preserve_default=False,
        ),
    ]
